"""
SentinelX - Database Manager
Handles all SQLite database operations
"""

import sqlite3
import csv
import os
from datetime import datetime

# Path to the database file
DB_PATH = os.path.join(os.path.dirname(__file__), 'sentinelx.db')


class DatabaseManager:
    """Manages all database operations for SentinelX"""

    def __init__(self):
        self.db_path = DB_PATH
        self.init_database()

    def get_connection(self):
        """Create and return a database connection"""
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row  # Access columns by name
        return conn

    def init_database(self):
        """Create all tables if they don't exist"""
        conn = self.get_connection()
        cursor = conn.cursor()

        # Table 1: SSH Events (honeypot logs)
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS ssh_events (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                ip_address  TEXT NOT NULL,
                username    TEXT NOT NULL,
                password    TEXT NOT NULL,
                timestamp   DATETIME DEFAULT CURRENT_TIMESTAMP,
                session_id  TEXT UNIQUE
            )
        ''')

        # Table 2: Port Scan Events (sniffer logs)
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS port_scan_events (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                ip_address  TEXT NOT NULL,
                port_number INTEGER NOT NULL,
                timestamp   DATETIME DEFAULT CURRENT_TIMESTAMP,
                packet_type TEXT DEFAULT 'SYN'
            )
        ''')

        # Table 3: Alerts (generated by detection engine)
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS alerts (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                ip_address  TEXT NOT NULL,
                attack_type TEXT NOT NULL,
                severity    TEXT NOT NULL,
                timestamp   DATETIME DEFAULT CURRENT_TIMESTAMP,
                details     TEXT,
                resolved    BOOLEAN DEFAULT 0
            )
        ''')

        # Table 4: Blocked IPs
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS blocked_ips (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                ip_address  TEXT NOT NULL UNIQUE,
                reason      TEXT,
                blocked_at  DATETIME DEFAULT CURRENT_TIMESTAMP,
                blocked_by  TEXT DEFAULT 'admin'
            )
        ''')

        conn.commit()
        conn.close()
        print("[DB] Database initialized successfully")

    # ─────────────────────────────────────────
    # SSH EVENTS
    # ─────────────────────────────────────────

    def insert_ssh_event(self, ip_address, username, password, session_id):
        """Log a new SSH connection attempt"""
        conn = self.get_connection()
        cursor = conn.cursor()
        try:
            cursor.execute('''
                INSERT INTO ssh_events (ip_address, username, password, session_id)
                VALUES (?, ?, ?, ?)
            ''', (ip_address, username, password, session_id))
            conn.commit()
            print(f"[DB] SSH event logged: {ip_address} tried {username}/{password}")
        except sqlite3.IntegrityError:
            pass  # Duplicate session_id, ignore
        finally:
            conn.close()

    def get_ssh_events(self, limit=100):
        """Retrieve recent SSH events"""
        conn = self.get_connection()
        cursor = conn.cursor()
        cursor.execute('''
            SELECT * FROM ssh_events
            ORDER BY timestamp DESC
            LIMIT ?
        ''', (limit,))
        events = [dict(row) for row in cursor.fetchall()]
        conn.close()
        return events

    # ─────────────────────────────────────────
    # PORT SCAN EVENTS
    # ─────────────────────────────────────────

    def insert_port_scan_event(self, ip_address, port_number, packet_type='SYN'):
        """Log a port scan packet"""
        conn = self.get_connection()
        cursor = conn.cursor()
        cursor.execute('''
            INSERT INTO port_scan_events (ip_address, port_number, packet_type)
            VALUES (?, ?, ?)
        ''', (ip_address, port_number, packet_type))
        conn.commit()
        conn.close()

    def get_port_scan_events(self, limit=100):
        """Retrieve recent port scan events"""
        conn = self.get_connection()
        cursor = conn.cursor()
        cursor.execute('''
            SELECT * FROM port_scan_events
            ORDER BY timestamp DESC
            LIMIT ?
        ''', (limit,))
        events = [dict(row) for row in cursor.fetchall()]
        conn.close()
        return events

    # ─────────────────────────────────────────
    # ALERTS
    # ─────────────────────────────────────────

    def insert_alert(self, ip_address, attack_type, severity, details=''):
        """Create a new security alert"""
        conn = self.get_connection()
        cursor = conn.cursor()
        cursor.execute('''
            INSERT INTO alerts (ip_address, attack_type, severity, details)
            VALUES (?, ?, ?, ?)
        ''', (ip_address, attack_type, severity, details))
        alert_id = cursor.lastrowid
        conn.commit()
        conn.close()
        print(f"[DB] Alert created: {attack_type} | {severity} | {ip_address}")
        return alert_id

    def get_alerts(self, severity=None, limit=100):
        """Retrieve alerts, optionally filtered by severity"""
        conn = self.get_connection()
        cursor = conn.cursor()
        if severity:
            cursor.execute('''
                SELECT * FROM alerts
                WHERE severity = ?
                ORDER BY timestamp DESC
                LIMIT ?
            ''', (severity, limit))
        else:
            cursor.execute('''
                SELECT * FROM alerts
                ORDER BY timestamp DESC
                LIMIT ?
            ''', (limit,))
        alerts = [dict(row) for row in cursor.fetchall()]
        conn.close()
        return alerts

    def get_alert_statistics(self):
        """Get statistics for the dashboard"""
        conn = self.get_connection()
        cursor = conn.cursor()

        # Total alerts
        cursor.execute('SELECT COUNT(*) as total FROM alerts')
        total = cursor.fetchone()['total']

        # Alerts by severity
        cursor.execute('''
            SELECT severity, COUNT(*) as count
            FROM alerts
            GROUP BY severity
        ''')
        by_severity = {row['severity']: row['count']
                      for row in cursor.fetchall()}

        # Alerts by type
        cursor.execute('''
            SELECT attack_type, COUNT(*) as count
            FROM alerts
            GROUP BY attack_type
        ''')
        by_type = {row['attack_type']: row['count']
                  for row in cursor.fetchall()}

        # Top 5 attacker IPs
        cursor.execute('''
            SELECT ip_address, COUNT(*) as count
            FROM alerts
            GROUP BY ip_address
            ORDER BY count DESC
            LIMIT 5
        ''')
        top_ips = [dict(row) for row in cursor.fetchall()]

        # Alerts per hour (last 24h)
        cursor.execute('''
            SELECT strftime('%H', timestamp) as hour,
                   COUNT(*) as count
            FROM alerts
            WHERE timestamp >= datetime('now', '-24 hours')
            GROUP BY hour
            ORDER BY hour
        ''')
        per_hour = [dict(row) for row in cursor.fetchall()]

        conn.close()
        return {
            'total': total,
            'by_severity': by_severity,
            'by_type': by_type,
            'top_ips': top_ips,
            'per_hour': per_hour
        }

    # ─────────────────────────────────────────
    # EXPORT
    # ─────────────────────────────────────────

    def export_alerts_csv(self, filepath='logs/alerts_export.csv'):
        """Export all alerts to CSV file"""
        alerts = self.get_alerts(limit=10000)
        if not alerts:
            return False
        with open(filepath, 'w', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=alerts[0].keys())
            writer.writeheader()
            writer.writerows(alerts)
        print(f"[DB] Exported {len(alerts)} alerts to {filepath}")
        return True

    # ─────────────────────────────────────────
    # BLOCKED IPs
    # ─────────────────────────────────────────

    def block_ip(self, ip_address, reason='Manual block by admin'):
        """Add an IP to the blocked list"""
        conn = self.get_connection()
        cursor = conn.cursor()
        try:
            cursor.execute('''
                INSERT OR IGNORE INTO blocked_ips
                (ip_address, reason)
                VALUES (?, ?)
            ''', (ip_address, reason))
            conn.commit()
            affected = cursor.rowcount
            print(f"[DB] IP blocked: {ip_address}")
            return affected > 0
        except Exception as e:
            print(f"[DB] Block IP error: {e}")
            return False
        finally:
            conn.close()

    def unblock_ip(self, ip_address):
        """Remove an IP from the blocked list"""
        conn = self.get_connection()
        cursor = conn.cursor()
        cursor.execute(
            'DELETE FROM blocked_ips WHERE ip_address = ?',
            (ip_address,)
        )
        conn.commit()
        conn.close()
        print(f"[DB] IP unblocked: {ip_address}")

    def get_blocked_ips(self):
        """Return all blocked IPs"""
        conn = self.get_connection()
        cursor = conn.cursor()
        cursor.execute(
            'SELECT * FROM blocked_ips ORDER BY blocked_at DESC'
        )
        ips = [dict(row) for row in cursor.fetchall()]
        conn.close()
        return ips

    def is_ip_blocked(self, ip_address):
        """Check if an IP is already blocked"""
        conn = self.get_connection()
        cursor = conn.cursor()
        cursor.execute(
            'SELECT id FROM blocked_ips WHERE ip_address = ?',
            (ip_address,)
        )
        result = cursor.fetchone()
        conn.close()
        return result is not None